#!/bin/bash

APPIMAGE_ROOT="$(dirname "$(readlink -f "$0")")"

VERSION=$(readlink "$APPIMAGE_ROOT/bin/emacs" | sed -e 's/emacs-//')

export EMACSLOADPATH="$APPIMAGE_ROOT/share/emacs/$VERSION/lisp"
export EMACSDATA="$APPIMAGE_ROOT/share/emacs/$VERSION/etc"
export EMACSDOC="$APPIMAGE_ROOT/share/emacs/$VERSION/etc"
export EMACSPATH="$APPIMAGE_ROOT/libexec/emacs/$VERSION/x86_64-pc-linux-gnu"
export PATH="$APPIMAGE_ROOT/bin:$PATH"

# check --emacs-appimage-run-as argument
if [ "$1" = "--emacs-appimage-run-as" ]; then
    shift
    CMD="$1"
    shift
    exec "$APPIMAGE_ROOT/bin/$CMD" "$@"
fi

exec "$APPIMAGE_ROOT/bin/emacs" "$@"
