#!/bin/bash

# https://docs.appimage.org/packaging-guide/environment-variables.html#id2

APPIMAGE_ROOT="$APPDIR"

unset APPDIR
unset APPIMAGE
unset OWD
unset ARGV0

VERSION=$(readlink "$APPIMAGE_ROOT/bin/emacs" | sed -e 's/emacs-//')

export EMACSLOADPATH="$APPIMAGE_ROOT/share/emacs/$VERSION/lisp"
export EMACSDATA="$APPIMAGE_ROOT/share/emacs/$VERSION/etc"
export EMACSDOC="$APPIMAGE_ROOT/share/emacs/$VERSION/etc"
export EMACSPATH="$(echo "$APPIMAGE_ROOT"/libexec/emacs/$VERSION/*)"
export PATH="$APPIMAGE_ROOT/bin:$PATH"

# check --emacs-appimage-run-as argument
if [ "$1" = "--emacs-appimage-run-as" ]; then
    shift
    CMD="$1"
    shift
    exec "$APPIMAGE_ROOT/bin/$CMD" "$@"
fi

exec "$APPIMAGE_ROOT/bin/emacs" "$@"
