on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string

jobs:
  prepare-builder-docker:
    runs-on: ${{ inputs.arch == 'aarch64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: blahgeek
        password: ${{ secrets.dockerhub_token }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and export
      uses: docker/build-push-action@v6
      with:
        context: .
        cache-from: type=registry,ref=blahgeek/emacs-appimage-builder:${{ inputs.arch }}-cache
        cache-to: type=registry,ref=blahgeek/emacs-appimage-builder:${{ inputs.arch }}-cache,mode=max
        tags: builder-image:latest
        outputs: type=docker,dest=/tmp/${{ inputs.arch }}-builder-image.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.arch }}-builder-image
        path: /tmp/${{ inputs.arch }}-builder-image.tar
        compression-level: 0

  prepare-tester-docker-ubuntu2004:
    runs-on: 'ubuntu-latest'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and export
      uses: docker/build-push-action@v5
      with:
        file: tests/Dockerfile.ubuntu2004
        # cache-from: type=gha
        # cache-to: type=gha,mode=max
        tags: tester-image_ubuntu2004:latest
        outputs: type=docker,dest=/tmp/${{ inputs.arch }}-tester-image_ubuntu2004.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.arch }}-tester-image_ubuntu2004
        path: /tmp/${{ inputs.arch }}-tester-image_ubuntu2004.tar
        compression-level: 0

  prepare-tester-docker-archlinux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and export
      uses: docker/build-push-action@v5
      with:
        file: tests/Dockerfile.archlinux
        # cache-from: type=gha
        # cache-to: type=gha,mode=max
        tags: tester-image_archlinux:latest
        outputs: type=docker,dest=/tmp/${{ inputs.arch }}-tester-image_archlinux.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.arch }}-tester-image_archlinux
        path: /tmp/${{ inputs.arch }}-tester-image_archlinux.tar
        compression-level: 0
